export const pokemonStarters = [
   {
      pokeNum: "0004",
      pokeName:"Charmander",
      pokeTitle: "Lizard Pokémon",
      pokeType: ["fire"],
      pokeTypeImg:"pokemon-types/FIRE.png",
      pokeHeight: ["2′00″","0.6 m"],
      pokeWeight: ["18.7 lbs.", "8.5 kg"],
      pokeDesc:"The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.",
      isSprite: false,
      pokeImage: "pokemon-images/0004Charmander.png",
   },
   {
      pokeNum: "0004",
      pokeName:"Charmander",
      pokeTitle: "Lizard Pokémon",
      pokeType: ["fire"],
      pokeTypeImg:"pokemon-types/FIRE.png",
      pokeHeight: ["2′00″","0.6 m"],
      pokeWeight: ["18.7 lbs.", "8.5 kg"],
      pokeSprite:"poke-sprites/char-sprite.png",
      pokeDesc:"The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.",
      isSprite: true,
      pokeImage: "pokemon-images/0004Charmander.png",
   },

   {
      pokeNum: "0155",
      pokeName:"Cyndaquil",
      pokeTitle: "Fire Mouse Pokémon",
      pokeType: ["fire"],
      pokeTypeImg:"pokemon-types/FIRE.png",
      pokeHeight: ["1′08″","0.5 m"],
      pokeWeight: ["17.4 lbs.", "7.9 kg"],
      pokeSprite:"poke-sprites/cynda-sprite.png",
      pokeDesc:"Cyndaquil protects itself by flaring up the flames on its back. The flames are vigorous if the Pokémon is angry. However, if it is tired, the flames splutter fitfully with incomplete combustion.",
      isSprite: true,
      pokeImage: "pokemon-images/0155Cyndaquil.png",
   },

   {
      pokeNum: "0255",
      pokeName:"Torchic",
      pokeTitle: "Chick Pokémon",
      pokeType: ["fire"],
      pokeTypeImg:"pokemon-types/FIRE.png",
      pokeHeight: ["1′04″","0.4 m"],
      pokeWeight: ["5.5 lbs.", "2.5 kg"],
      pokeSprite:"poke-sprites/torchic-sprite.png",
      pokeDesc:"Torchic has a place inside its body where it keeps its flame. Give it a hug - it will be glowing with warmth. This Pokémon is covered all over by a fluffy coat of down.",
      isSprite: true,
      pokeImage: "pokemon-images/0255Torchic.png",
   },

   {
      pokeNum: "0390",
      pokeName:"Chimchar",
      pokeTitle: "Chimp Pokémon",
      pokeType: ["fire"],
      pokeTypeImg:"pokemon-types/FIRE.png",
      pokeHeight: ["1′08″","0.5 m"],
      pokeWeight: ["13.7 lbs.", "6.2 kg"],
      pokeSprite:"poke-sprites/chimchar-sprite.png",
      pokeDesc:"It agilely scales sheer cliffs to live atop craggy mountains. Its fire is put out when it sleeps.",
      isSprite: true,
      pokeImage: "pokemon-images/0390Chimchar.png",
   },

   {
      pokeNum: "0007",
      pokeName:"Squirtle",
      pokeTitle: "Tiny Turtle Pokémon",
      pokeType: ["water"],
      pokeTypeImg:"pokemon-types/WATER.png",
      pokeHeight: ["1′08″","0.5 m"],
      pokeWeight: ["19.8 lbs.", "9.0 kg"],
      pokeSprite:"poke-sprites/squirtle-sprite.png",
      pokeDesc:"Squirtle's shell is not merely used for protection. The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds.",
      isSprite: true,
      pokeImage: "pokemon-images/0007Squirtle.png",
   },
  
   {
      pokeNum: "0158",
      pokeName:"Totodile",
      pokeTitle: "Big Jaw Pokémon",
      pokeType: ["water"],
      pokeTypeImg:"pokemon-types/WATER.png",
      pokeHeight: ["2′00″","0.6 m"],
      pokeWeight: ["20.9 lbs.", "9.5 kg"],
      pokeSprite:"poke-sprites/totodile-sprite.png",
      pokeDesc:"Despite its small body, Totodile's jaws are very powerful. While it may think it is just playfully nipping, its bite has enough strength to cause serious injury.",
      isSprite: true,
      pokeImage: "pokemon-images/0158Totodile.png",
   },
 
   {
      pokeNum: "0258",
      pokeName:"Mudkip",
      pokeTitle: "Mud Fish Pokémon",
      pokeType: ["water"],
      pokeTypeImg:"pokemon-types/WATER.png",
      pokeHeight: ["1′04″","0.4 m"],
      pokeWeight: ["16.8 lbs.", "7.6 kg"],
      pokeSprite:"poke-sprites/mudkip-sprite.png",
      pokeDesc:"The fin on Mudkip's head acts as highly sensitive radar. Using this fin to sense movements of water and air, this Pokémon can determine what is taking place around it without using its eyes.",
      isSprite: true,
      pokeImage: "pokemon-images/0258Mudkip.png",
   },

   {
      pokeNum: "0393",
      pokeName:"Piplup",
      pokeTitle: "Penguin Pokémon",
      pokeType: ["water"],
      pokeTypeImg:"pokemon-types/WATER.png",
      pokeHeight: ["1′04″","0.4 m"],
      pokeWeight: ["11.5 lbs.", "5.2 kg"],
      pokeSprite:"poke-sprites/piplup-sprite.png",
      pokeDesc:"It lives along shores in northern countries. A skilled swimmer, it dives for over 10 minutes to hunt.",
      isSprite: true,
      pokeImage: "pokemon-images/0393Piplup.png",
   },

   {
      pokeNum: "0001",
      pokeName:"Bulbasaur",
      pokeTitle: "Seed Pokémon",
      pokeType: ["grass"],
      pokeTypeImg:"pokemon-types/GRASS.png",
      pokeHeight: ["2′04″","0.7 m"],
      pokeWeight: ["15.2 lbs.", "6.9 kg"],
      pokeSprite:"poke-sprites/bulb-sprite.png",
      pokeDesc:"Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.",
      isSprite: true,
      pokeImage: "pokemon-images/0001Bulbasaur.png",
   },

   {
      pokeNum: "0152",
      pokeName:"Chikorita",
      pokeTitle: "Leaf Pokémon",
      pokeType: ["grass"],
      pokeTypeImg:"pokemon-types/GRASS.png",
      pokeHeight: ["2′11″","0.9 m"],
      pokeWeight: ["14.1 lbs.", "6.4 kg"],
      pokeSprite:"poke-sprites/chiko-sprite.png",
      pokeDesc:"In battle, Chikorita waves its leaf around to keep the foe at bay. However, a sweet fragrance also wafts from the leaf, becalming the battling Pokémon and creating a cozy, friendly atmosphere all around.",
      isSprite: true,
      pokeImage: "pokemon-images/0152Chikorita.png",
   },

   {
      pokeNum: "0252",
      pokeName:"Treecko",
      pokeTitle: "Wood Gecko Pokémon",
      pokeType: ["grass"],
      pokeTypeImg:"pokemon-types/GRASS.png",
      pokeHeight: ["1′08″","0.5 m"],
      pokeWeight: ["11.0 lbs.", "5.0 kg"],
      pokeSprite:"poke-sprites/treeko-sprite.png",
      pokeDesc:"Treecko is cool, calm, and collected - it never panics under any situation. If a bigger foe were to glare at this Pokémon, it would glare right back without conceding an inch of ground.",
      isSprite: true,
      pokeImage: "pokemon-images/0252Treecko.png",
   },

   {
      pokeNum: "0387",
      pokeName:"Turtwig",
      pokeTitle: "Tiny Leaf Pokémon",
      pokeType: ["grass"],
      pokeTypeImg:"pokemon-types/GRASS.png",
      pokeHeight: ["1′04″","0.4 m"],
      pokeWeight: ["22.5 lbs.", "10.2 kg"],
      pokeSprite:"poke-sprites/turtwig-sprite.png",
      pokeDesc:"Turtwig undertakes photosynthesis with its body, making oxygen. The leaf on its head wilts if it is thirsty.",
      isSprite: true,
      pokeImage: "pokemon-images/0387Turtwig.png",
   },

]